
[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "Buttonless"
dynamic_title = true
opacity = 0.8
startup_mode = "Windowed"
title = "Alacritty"

[window.padding]
x = 16
y = 16

[general]
live_config_reload = true
import = ["~/.config/alacritty/dracula.toml"]
